name: calentre
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  go_router: ^12.0.1
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.5
  equatable: ^2.0.5
  feature_notifier: ^1.0.71
  animate_gradient: ^0.0.2+1
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  dio: ^5.3.3
  supabase_flutter: ^1.10.24
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  web_toast: ^1.0.4-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - asset/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
